In [4]:
#Write a function so that the columns of the output matrix are powers of the input vector.

import numpy as np

def vndrmnde_mtx():
    print("Enter the list of comma separated numbers")
    input_lst = input(">>>")
    lst = list(map(int,input_lst.split(',')))
    print(lst)
    print("Enter the number of columns required in the matrix")
    num_of_cols = int(input(">>>"))
    x = np.array(lst)
    #Calling the inbuild Vander function to create the output matrix
    mtx1 = np.vander(x,num_of_cols)
    print("Output Matrix with Increasing as False")
    print(mtx1)
    #Calling with increasing as True
    print("Output Matrix with Increasing as True")
    mtx1 = np.vander(x,num_of_cols,increasing=True)
    print(mtx1)

vndrmnde_mtx()

Please enter the list of comma separated numbers
>>>1,6,3,8
[1, 6, 3, 8]
Please enter the number of columns required in the matrix
>>>4
Output Matrix with Increasing as False
[[  1   1   1   1]
 [216  36   6   1]
 [ 27   9   3   1]
 [512  64   8   1]]
Output Matrix with Increasing as True
[[  1   1   1   1]
 [  1   6  36 216]
 [  1   3   9  27]
 [  1   8  64 512]]


In [25]:
# Write a function to find moving average in an array over a window:

import sys
import numpy as np

def moving_avg():
    print("Enter the sequence of numbers")
    input_seq = input(">>>>")
    print("Enter the Window size")
    win_size = int(input(">>>>"))
    if win_size <= 0:
        sys.exit("Window size should be greater than Zero(0)")
    input_lst = list(map(int,input_seq.split(',')))
    len_lst = len(input_lst)
    print("Length of input list: {}".format(len_lst))
    x = np.array(input_lst)
    out_seq = np.convolve(x,np.ones(win_size, dtype = int)/win_size,'valid').astype('int32')
    print("The Output Sequence is as below")
    print("######################################")
    print(out_seq)
    print("Length of Output Sequence: {}".format(len(out_seq)))

moving_avg()

Enter the sequence of numbers
>>>>3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150
Enter the Window size
>>>>3
Length of input list: 13
The Output Sequence is as below
######################################
[  5   4   5   6   9  28  49  72  84  93 116]
Length of Output Sequence: 11
